name: CI workflow

# 1. Workflow triggers
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. Jobs configuration
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      # 3. Checkout step
      - name: Checkout
        uses: actions/checkout@v3

      # 4. Install Dependencies step
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Lint step (Required for your submission)
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 6. Unit Test step (Required for your submission)
      - name: Run unit tests with nose
        run: |
          pip install nose
          nosetests